# Generated by Django 5.2.6 on 2025-09-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_alter_joblinks_user_friendlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firebase_uid',
            field=models.CharField(default='xxxxx', max_length=50),
        ),
    ]
