# Generated by Django 5.2.6 on 2025-09-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_user_firebase_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlist',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted')], default='None', max_length=20),
        ),
    ]
