# Generated by Django 5.2.6 on 2025-09-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0005_alter_friendlist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firebase_uid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
